title: Taemin Code
description: Taemin's personal site and blogs
baseurl: "" # important: keep this empty for user sites
url: "https://taemincode.github.io"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-last-modified-at
